pymongo: use projection=[] instead of fields={}
With current pymongo==3.13.0, was causing exception:
    TypeError: __init__() got an unexpected keyword argument 'fields'

Not sure when pymongo API changed; oldest doc I found online
https://pymongo.readthedocs.io/en/3.5.1/api/pymongo/collection.html#pymongo.collection.Collection.find
which doesn't mention `fields=` only `projection=`.

Change from {x: 1} to ['x'] style is cosmetic, reads less magic to me,
but `projection` arg supports both.